export const ActionTypes = {
    ADD_CART: "ADD_CART",
    INCREMENT: "INCREMENT",
    DECREMENT: "DECREMENT",
    DELETE: "DELETE",
    FETCH_DATA: "FETCH_DATA",
    LOADING: "LOADING",
    ADD_DELETE_STATUS: "ADD_DELETE_STATUS",
    ADD_DELETE_STATUS_POST: "ADD_DELETE_STATUS_POST"
}